frontend:
  build: ./apps/frontend
  volumes:
    - ./apps/frontend:/src
  ports:
   - "3000:3000"
  command: [npm, start]
api:
  build: ./apps/api
  volumes:
    - ./apps/api:/src
  ports:
    - "3001:3001"
  links:
    - mongodb
  command: [nodemon, start]
mongodb:
  image: mongo:3
  volumes:
    - ./runtime/mongo:/data/db
  ports:
    - "27017:27017"
mongoexpress:
  image: mongo-express:0.34
  links:
    - mongodb
  environment:
    ME_CONFIG_MONGODB_SERVER: mongodb
    ME_CONFIG_MONGODB_PORT: 27017
  ports:
    - "8082:8081"
docs:
  image: swaggerapi/swagger-ui:latest
  ports:
    - "8080:8080"
  environment:
    API_URL: http://localhost:3001/swagger/docs/api.json
